// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaFu7pid3hlZQG4SnTseULoQZd2_3wu5g',
    appId: '1:691867814663:web:ea3704804a103b4a4d13a2',
    messagingSenderId: '691867814663',
    projectId: 'casenextapp',
    authDomain: 'casenextapp.firebaseapp.com',
    storageBucket: 'casenextapp.firebasestorage.app',
    measurementId: 'G-6P9HXHQ92K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuZmhpk99wLNd6KVh1392AAtTyetd0k9g',
    appId: '1:691867814663:android:dfd8be04ee3bb8014d13a2',
    messagingSenderId: '691867814663',
    projectId: 'casenextapp',
    storageBucket: 'casenextapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfIfr6qMPm0kOL52zE-M_ItN1joe_pyAA',
    appId: '1:691867814663:ios:26fe9e4fddc783924d13a2',
    messagingSenderId: '691867814663',
    projectId: 'casenextapp',
    storageBucket: 'casenextapp.firebasestorage.app',
    iosBundleId: 'com.example.caseNext',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfIfr6qMPm0kOL52zE-M_ItN1joe_pyAA',
    appId: '1:691867814663:ios:26fe9e4fddc783924d13a2',
    messagingSenderId: '691867814663',
    projectId: 'casenextapp',
    storageBucket: 'casenextapp.firebasestorage.app',
    iosBundleId: 'com.example.caseNext',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaFu7pid3hlZQG4SnTseULoQZd2_3wu5g',
    appId: '1:691867814663:web:a2dcacf8319036af4d13a2',
    messagingSenderId: '691867814663',
    projectId: 'casenextapp',
    authDomain: 'casenextapp.firebaseapp.com',
    storageBucket: 'casenextapp.firebasestorage.app',
    measurementId: 'G-32GLFJD8FX',
  );
}
